services:
  agent-miner:
    image: redteamsubnet61/agent-miner:2.0.0-251224
    build:
      context: .
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      RT_MINER_AXON_PORT: ${RT_MINER_AXON_PORT:-8091}
      RT_BTCLI_WALLET_DIR: "${RT_BTCLI_WALLET_DIR}"
      RT_MINER_WALLET_NAME: ${RT_MINER_WALLET_NAME}
      RT_MINER_HOTKEY_NAME: ${RT_MINER_HOTKEY_NAME}
    env_file:
      - path: .env
        required: false
    volumes:
      - "${RT_BTCLI_WALLET_DIR}:${RT_BTCLI_WALLET_DIR}"
      - "${RT_MINER_COMMIT_FILE_PATH}:/app/agent-miner/miner/config/active_commit.yaml"
      - "./volumes/storage/agent-miner/logs:/var/log/agent-miner"
      - "./volumes/storage/agent-miner/data:/var/lib/agent-miner"
    ports:
      - "${RT_MINER_AXON_PORT:-8091}:${RT_MINER_AXON_PORT:-8091}"
    tty: true
