services:
  agent-miner:
    image: redteamsubnet61/agent-miner:3.0.3-260218
    build:
      context: .
    restart: unless-stopped
    network_mode: bridge
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      RT_MINER_AXON_PORT: ${RT_MINER_AXON_PORT:-8091}
      RT_BTCLI_WALLET_DIR: "${RT_BTCLI_WALLET_DIR:?error}"
      RT_MINER_WALLET_NAME: ${RT_MINER_WALLET_NAME:?error}
      RT_MINER_HOTKEY_NAME: ${RT_MINER_HOTKEY_NAME:?error}
    env_file:
      - path: .env
        required: false
    volumes:
      - "${RT_BTCLI_WALLET_DIR:?error}:${RT_BTCLI_WALLET_DIR:?error}"
      - "${RT_MINER_COMMIT_FILE_PATH:-./volumes/configs/agent-miner/active_commit.yaml}:/app/agent-miner/miner/config/active_commit.yaml"
      - "./volumes/storage/agent-miner/logs:/var/log/agent-miner"
      - "./volumes/storage/agent-miner/data:/var/lib/agent-miner"
    ports:
      - "${RT_MINER_AXON_PORT:-8091}:${RT_MINER_AXON_PORT:-8091}"
    tty: true
