services:
  agent-miner:
    image: redteamsubnet61/agent-miner:2.0.0-251224
    build:
      context: .
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      RT_MINER_PORT: ${RT_MINER_PORT:-47920}
    env_file:
      - path: .env
        required: false
    volumes:
      - "./volumes/storage/sidecar-btcli/data:/var/lib/sidecar-btcli"
      - "./volumes/storage/agent-miner/logs:/var/log/agent-miner"
      - "./volumes/storage/agent-miner/data:/var/lib/agent-miner"
    ports:
      - "${RT_MINER_PORT:-8088}:${RT_MINER_PORT:-8088}"
    tty: true
